/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class App {
    // UnusedPrivateField
    private String unusedField = "unused";

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // SystemPrintln
        System.out.println(new App().getGreeting());
    }
}
